aws:
  region: ap-northeast-1
  access_key_id: <%= '11111111' %>
  secret_access_key: <%= '44' %>
  account_id: 111111111
database_url_format: "mysql2://#{db_user}:#{db_password}@#%{db_endpoint}/#{db_name}?pool=5"
db_instance:
  db_parameter_group_name: default
  db_cluster_parameter_group_name: default
  publicly_accessible: false
  source_instance:
    identifier: a
    cluster_identifier: b
  available_types:
    - db.r4.large
    - db.r4.2xlarge
    - db.r4.3xlarge
  default_instance_type: db.r4.large
